name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt || echo "No requirements"

      - name: Build EXE with icon
        run: |
          pyinstaller --onefile --noconsole --icon=icon.ico calculator.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-exe
          path: dist/CalculatorApp.exe

